-- products.sql – RaktarPro
-- REPLACE INTO: bármikor újrafuttatható, nem dob hibát.
-- Importálás előtt importáld a db_schema.sql-t!
-- Kategória IDs: 1=Mobil, 2=Laptop, 3=TV & Monitor, 4=Fejhallgató,
--                5=Fotózás, 6=Okoseszközök, 7=PC Kiegészítők, 8=Gaming, 9=Hálózat, 10=Hangszóró

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

REPLACE INTO `products`
  (`id`, `sku`, `name`, `description`, `image_url`, `category_id`, `supplier_id`, `unit_price`, `weight`, `stock`)
VALUES
(1,  'P001', 'iPhone 15 Pro',        'Az iPhone 15 Pro nem csupán egy telefon – ez az az eszköz, ami miatt az ember elgondolkodik, hogy valaha is kellett-e más. A légipari titánium keret miatt szinte hihetetlenül könnyű a méretéhez képest, mégis tart egy életen át. A 48 MP-es főszenzor gyenge fényben, portréknál és tájakban egyaránt természetes, részletgazdag képeket ad, a 3× optikai zoom diszkrét és gyors. ProRAW és ProRes videófelvétellel profi szinten szerkeszthet az anyagokon. Az Action gomb egy kattintással bármit előhív, az A17 Pro chip pedig gyorsabb és hűvösebb marad játék vagy videószerkesztés közben is. iOS frissítések évekig garantálják, hogy a telefon naprakész és biztonságos maradjon.',         'https://image.alza.cz/products/HRI045b1/HRI045b1.jpg?width=500&height=500',      1, 1, 489600.00, 0.187, 21),
(2,  'P002', 'Samsung Galaxy S24 Ultra', 'A Galaxy S24 Ultra az a telefon, amit ha egyszer kézbe vesz, nehéz letenni. A beépített S Pen minden más kiegészítőt feleslegessé tesz – vázlatrajzolástól valós idejű fordításig mindent kezel. A 200 MP-es főszenzor annyira részletes képeket ad, hogy utólag is szabadon vágható, közelíthető az anyag. A Galaxy AI funkciók – képszerkesztés, Chat Assist, körlevélfordítás – napról napra megkönnyítik a munkát. A Snapdragon 8 Gen 3 chip és az 5000 mAh-s akku 45 W-os gyorstöltéssel gondoskodik arról, hogy soha ne hagyja cserben.',                                                           'https://p1.akcdn.net/full/1240638079.samsung-galaxy-s24-ultra-5g-1tb-12gb-ram-dual-sm-s928b.jpg',  1, 393990, 393990.00, 0.232, 22),
(3,  'P003', 'ASUS ROG Strix G16 (2024)', 'Ha gaming laptopot keres, de nem akar kompromisszumot kötni a teljesítménnyel, az ROG Strix G16 az egyik legjobb választás ezen az áron. Az RTX 4060 videokártya gond nélkül kezeli a modern AAA játékokat, a 165 Hz-es QHD kijelző pedig valóban érezhetően simább képet ad, mint az átlagos kijelzők. Az Intel Core i7 és 16 GB DDR5 RAM nem csak játékban, de videószerkesztésben és renderelésben is kiemelkedő. Az MUX Switch direkt GPU módban maximális teljesítményt biztosít, a háromzónás RGB háttérvilágítás pedig szabadon személyre szabható.',                                                  'https://images.euronics.hu/product_images/800x600/resize/1_jm1148rk.png?v=3',     8, 2, 599990.00, 2.500,  4),
(4,  'P004', 'MacBook Air M2 (2023)', 'A MacBook Air M2 az a laptop, amit szinte mindenki szeretne, aki Macet akar. Ventilátor nincs benne, tehát teljesen csendben működik – mégis meglepően gyors, és felülmúlja a korábbi Intel alapú MacBookokat. A Liquid Retina kijelző éles és pontos, a MagSafe 3 töltő gyors és biztonságos, az akku akár 18 óráig bírja egy töltéssel. Csupán 1,24 kg és 11 mm vékony – mindennapi munkára, kreatív feladatokra és tanulásra egyaránt kiváló választás.',                                                                       'https://images.euronics.hu/product_images/800x600/resize/s1_0gljqn0o.jpeg?v=3',     2, 369990, 369990.00, 1.240, 24),
(5,  'P005', 'Dell XPS 13 Plus (2023)', 'Az XPS 13 Plus az a laptop, amit a dizájnja miatt is megszeret az ember, de a teljesítménye sem okoz csalódást. A szinte keret nélküli OLED panel vibrálóan élénk és pontos képet ad, a billentyűzetbe olvadt kapacitív érintősáv haptic visszajelzéssel egészen más kategóriát képvisel. Az Intel Core i7 és 16 GB LPDDR5 RAM a legtöbb feladatot könnyedén elvégzi. Mindössze 1,24 kg, két Thunderbolt 4 port és kb. 10 óra üzemidő – utazáshoz és irodai munkához egyaránt tökéletes.',                                               'https://images.euronics.hu/product_images/800x600/resize/1dell_140rqx64.png?v=3',   2, 2, 549990.00, 1.240, 25),
(6,  'P006', 'HP Pavilion 15-eh3 (2023)', 'Ha egyszerűen csak egy jól működő, megbízható laptopot keres mindennapi használatra, a HP Pavilion 15 pontosan erre való. Nagy a kijelzője, kényelmes a billentyűzete, az AMD Ryzen 7 processzor és 16 GB RAM pedig gyors és energiahatékony a napi feladatokhoz. USB-C, három USB-A, HDMI és kártyaolvasó is megtalálható rajta, Windows 11 Home előtelepítve. Böngészés, iroda, videóhívás – minden gond nélkül megy, nehezebb feladatokhoz is megállja a helyét.',                                                         'https://images.euronics.hu/product_images/800x600/resize/1_0bxnxfwe.png?v=3',     2, 2, 249990.00, 1.750, 26),
(7,  'P007', 'Lenovo ThinkPad X1 Carbon Gen 11', 'A ThinkPad X1 Carbon az a laptop, amire az irodai szakemberek évek óta esküsznek – legendás megbízhatóság, kompromisszummentesen. Alig 1,12 kg, és katonai szabványoknak megfelelő védelemmel érkezik extrém hideg, meleg, por és ütés ellen egyaránt. A 14 colos OLED kijelző éles és szemkímélő, a billentyűzet a legjobb laptopbillentyűzetek közé tartozik. Az Intel Core i7 vPro és a 57 Wh-s akku kb. 15 óra valódi üzemidőt biztosít, ujjlenyomatolvasóval és IR kamerával kiegészítve.',                                                    'https://images.euronics.hu/product_images/800x600/resize/1_9bm45yxi.jpg?v=3',        2, 2, 649990.00, 1.120,  3),
(8,  'P008', 'Sony WH-1000XM5',      'Ha sokat utazik vagy zajos helyen dolgozik, a WH-1000XM5 az, amit keresett. A zajszűrése annyira hatékony, hogy repülőn is úgy érzi magát, mintha egy hangstúdióban ülne. A memóriahab párnák puhák és szellőzők, órákon át kényelmes a viselése. Az LDAC kodek Hi-Res minőségű hangot biztosít, a Multipoint csatlakozás pedig egyszerre két eszközzel párosítható. Mindössze 3 perc töltéssel 3 óra extra üzemidőt kap, teljes töltéssel 30 óra ANC-vel.',                                              'https://images.euronics.hu/product_images/800x600/resize/111_wx83ssf0.jpg?v=4',     4, 3, 89990.00, 0.250, 28),
(9,  'P009', 'Apple AirPods Pro 2. gen', 'Az AirPods Pro 2 az a fülhallgató, amit egyszer feltesz, és nem akar levenni. Az Adaptív Transparencia mód valós időben szűri a zajokat, mégis átengedi a fontos hangokat. A Spatial Audio funkció a zenét és a filmeket fizikailag körülötte helyezi el – élménye teljesen más, mint hagyományos fülhallgatónál. USB-C töltőtok, IP54 védettség, 6 óra önálló üzemidő ANC-vel, a tokkal együtt 30+ óra. Ha iPhone-ja van, ez a természetes választás.',                                  'https://images.euronics.hu/product_images/800x600/resize/1_rcr2ctja.jpg?v=3',      4, 3, 99990.00, 0.061, 29),
(10, 'P010', 'JBL Charge 5',         'A JBL Charge 5 az a bluetooth hangszóró, ami mindenhova elkíséri és sosem hagyja cserben. IP67 védettséggel nem kell félni az esőtől vagy a strandtól, a 7500 mAh belső akku 20 óra zenét biztosít egyetlen töltéssel. Közben a telefont is töltheti az USB-A kimeneten. A JBL Pro Sound basszusrendszere mélyen tömör, részletgazdag hangot ad szabadban is. PartyBoost funkcióval több JBL hangszóró összeköthető egyszerre.',                                                              'https://images.euronics.hu/product_images/800x600/resize/6_rru9cyfo.png?v=3',       10, 3,  44990.00, 0.960, 30),
(12, 'P012', 'LG OLED C3 65"',       'Az LG OLED C3 az egyik legjobb televízió, amit pénzért megvásárolhat. Az OLED panel minden pixele önmaga állítja elő és oltja el a fényt – tökéletes fekete, végtelen kontraszt, milliárd szín. Az α9 Gen6 AI processzor valós időben javítja a kép- és hangminőséget a tartalomtól függően. Négy HDMI 2.1 port biztosítja a PS5, Xbox és PC csatlakoztatását 4K/120Hz-en, G-Sync és FreeSync Premium Pro támogatással. Filmekhez, sorozatokhoz és komoly játékosoknak egyaránt az első választás.',                                                'https://images.euronics.hu/product_images/800x600/resize/1_qa5u5m70.png?v=4',      3, 4, 699990.00, 18.500,  5),
(13, 'E001', 'iPhone 15',            'Az iPhone 15 az első iPhone USB-C csatlakozóval – végre egyetlen töltő minden eszközhöz. A Dynamic Island az értesítéseket vizuálisan integrálja a kijelzőbe, a 48 MP-es főkamera és a Photonic Engine pedig minden fényviszonyban természetes képeket ad. Az A16 Bionic chip gyors és hatékony, az akku egész napra elegendő. MagSafe-kompatibilis, iOS frissítések évekig, mindössze 171 g – kényelmes egykézi használatra optimalizálva.',                                                                                      'https://image.alza.cz/products/HRI045b1/HRI045b1.jpg?width=500&height=500',          1, 1, 279990.00, 0.171, 40),
(14, 'E002', 'Samsung Galaxy S24',   'A Galaxy S24 a Samsung 2024-es kompakt csúcstelefonja, ahol semmiből sem engedtek. A Snapdragon 8 Gen 3 processzor és a beépített Galaxy AI – valós idejű fordítás, AI alapú képszerkesztés – napról napra megkönnyíti az életet. Az 50 MP-es háromkamerás rendszer éjszaka is megbízható, az optikai zoom diszkrét és pontos. 4000 mAh-s akku 25 W-os töltéssel, IP68 vízállóság, mindössze 167 g – kis méretben maximális teljesítmény.',                                                                                          'https://s13emagst.akamaized.net/products/64817/64816439/images/res_fdecd9733172144ab6b418e28f699e1c.jpg?width=720&height=720&hash=91C5F7015A569F5237D415DE60CD1451',        1, 1, 249990.00, 0.167, 35),
(15, 'E003', 'Xiaomi Redmi Note 13 Pro', 'A Redmi Note 13 Pro az ár-érték kategória egyik legjobb választása. A 200 MP-es szenzor olyan részletes képeket ad, amilyeneket korábban csak csúcstelefonoktól kapott az ember. A 120 Hz-es AMOLED kijelző éles, élénk és folyékony, a 67 W-os gyorstöltés pedig 40 perc alatt teljesen feltölti az 5100 mAh-s akkumulátort. A MediaTek Dimensity 7200 Ultra processzor gyors és energiahatékony, 256 GB belső tárhely bőségesen elegendő.',                                                                                                               'https://www.bestbyte.hu/Xiaomi_Redmi_Note_13_Pro_667_LTE_8256GB_DualSIM_fekete_okostelefon-i40357342.webp',       1, 1,  69990.00, 0.187, 45),
(16, 'E004', 'Google Pixel 8',       'A Pixel 8 a legtisztább Android élményt adja – 7 éves frissítési garancia, és Google AI funkciók, amiket más márkák még nem kínálnak. A Magic Eraser eltünteti a nem kívánt tárgyakat a képről, a Best Take mindenkit a legjobb arckifejezéssel mutat a csoportképen. A Tensor G3 chip az összes AI feladatot a telefonon hajtja végre, internet nélkül, privát módon. 4575 mAh akku, IP68 vízállóság és hat éves biztonsági frissítési garancia.',                                                                                                 'https://p1.akcdn.net/full/1201801729.google-pixel-8-5g-128gb-8gb-ram-dual.jpg',     1, 1, 219990.00, 0.187, 32),
(17, 'E005', 'MacBook Air M2',       'A MacBook Air M2 a legjobb mindennapi laptop azoknak, akik Macet akarnak. Teljesen csendes, ventilátor nélküli működéssel felülmúlja a korábbi Intel alapú MacBookokat. A Liquid Retina kijelző gyönyörű, a MagSafe 3 töltő gyors és biztonságos, az akku akár 18 óráig bírja egy töltéssel. 1,24 kg, mindössze 11 mm vékony, két Thunderbolt 4 porttal – mindennapi munkára és kreatív feladatokra egyaránt kiváló.',                                                                                                                                'https://images.euronics.hu/product_images/800x600/resize/s1_0gljqn0o.jpeg?v=3',   2, 2, 369990.00, 1.240, 20),
(18, 'E006', 'Dell XPS 13',          'Az XPS 13 a Dell prémium ultrabookja szinte keret nélküli OLED kijelzővel és könnyű alumínium házzal. Az Intel Core i7 és 16 GB RAM minden feladatot kezel, az OLED kijelző pontos és élénk képet ad, az 512 GB NVMe SSD villámgyors hozzáférést biztosít. Két Thunderbolt 4 port, kb. 12 óra üzemidő, mindössze 1,17 kg – utazáshoz és irodai munkához egyaránt tökéletes.',                                                                                                                                  'https://images.euronics.hu/product_images/800x600/resize/1dell_140rqx64.png?v=3',        2, 2, 499990.00, 1.170, 18),
(19, 'E007', 'Lenovo ThinkPad E14 Gen 5', 'A ThinkPad E14 a megbízható irodai laptop, amit Lenovo évtizedek óta tökéletesít. Az AMD Ryzen 7 processzor és 16 GB RAM a legtöbb irodai feladatot könnyedén kezeli, a kényelmes billentyűzet és az ujjlenyomatolvasó napi szinten megtérül. A 14 colos IPS kijelző csökkentett kék fénnyel védi a szemét hosszú munkamenetek során. USB-C, USB-A, HDMI és SD kártyaolvasó egyaránt megtalálható – megbízható, könnyen karbantartható választás.',                                                                                                               'https://images.euronics.hu/product_images/800x600/resize/1_9bm45yxi.jpg?v=3',       2, 2, 299990.00, 1.590, 22),
(20, 'E008', 'HP Envy 15',           'A HP Envy 15 az a laptop, ahol a teljesítmény és a prémium dizájn valóban találkozik. Az Intel Core i7 és a dedikált NVIDIA GeForce MX450 grafika lehetővé teszi a képszerkesztést és a könnyű videómontázst is. A 15,6 colos OLED kijelző élénk és szemkímélő, Dolby Vision támogatással, a Bang & Olufsen hangrendszer pedig minőségi hangzást nyújt. 16 GB RAM, 512 GB SSD, Thunderbolt 4 – prémium megjelenés, komoly teljesítmény.',                                                                                                                                      'https://images.euronics.hu/product_images/800x600/resize/1_0bxnxfwe.png?v=3',         2, 2, 399990.00, 1.990,  0),
(22, 'E010', 'LG 65" OLED TV',       'Az LG 65 colos OLED tévé a nappali szoba prémium médiaközpontja. Az önmegvilágító panel tökéletes feketéket és végtelen kontrasztarányt biztosít, amihez az LCD kijelzők nem érnek fel. Az α9 Gen6 AI processzor automatikusan optimalizálja a kép- és hangminőséget a tartalomtól függően. Négy HDMI 2.1 port PS5-höz, Xboxhoz és PC-hez egyaránt ideális, Dolby Vision IQ, Dolby Atmos és webOS felülettel.',                                                                                               'https://images.euronics.hu/product_images/800x600/resize/1_qa5u5m70.png?v=4',         3, 4, 699990.00, 19.500, 10),
(23, 'E011', 'Sony WH-1000XM5',      'A WH-1000XM5 a zajszűrős fejhallgatók egyik legelismertebb darabja. A zajszűrés repülőn és irodában egyaránt hatékony, a memóriahab párnák puhák, órákon át kényelmes a viselésük. Az LDAC kodek Hi-Res minőségű hangot biztosít, a Multipoint csatlakozás egyszerre két eszközzel párosítható. 30 óra üzemidő ANC-vel, 3 perc töltéssel 3 óra extra – és a Speak-to-Chat automatikusan szünetelteti a zenét, ha megszólal.',                                                                                                                                       'https://images.euronics.hu/product_images/800x600/resize/111_wx83ssf0.jpg?v=4',   4, 3, 59990.00, 0.250, 25),
(24, 'E012', 'Apple AirPods Pro 2. gen', 'Az AirPods Pro 2 a legjobb iOS-kompatibilis fülhallgató. Az Adaptív Transparencia mód intelligensen szűri a zajos környezetet, mégis átengedi a fontos hangokat. A Spatial Audio és a fejkövetés mozgáshoz igazított, háromdimenziós hangképet teremt. USB-C töltőtok, IP54 védettség a fülhallgatóra és a tokra egyaránt, 6 óra önálló üzemidő ANC-vel, tokkal együtt 30+ óra.',                                                                                                                          'https://images.euronics.hu/product_images/800x600/resize/1_rcr2ctja.jpg?v=3',    4, 3, 79990.00, 0.061, 30),
(26, 'E014', 'Logitech MX Master 3S', 'Az MX Master 3S az irodai és kreatív felhasználók egyik legkedveltebb egere – pontossága, kényelme és gombjainak száma egyedülálló. A 8000 DPI-s szenzor üvegen is tökéletesen működik, a MagSpeed görgő csendesen és villámgyorsan lapoz nagy dokumentumokban. Bluetooth és Logi Bolt vevőn keresztül egyszerre három eszközhöz csatlakoztatható, és könnyen váltható közöttük. Ergonomikus forma, 70 napos akkumulátor – macOS és Windows egyaránt támogatott.',                                                                                                               'https://images.euronics.hu/product_images/800x600/resize/s1_fbk4fyf7.jpg?v=2', 7, 5,  44990.00, 0.141, 50),
(27, 'E015', 'Keychron K8 Pro TKL',  'A Keychron K8 Pro a mechanikus billentyűzet-rajongók egyik kedvenc darabja. Hot-swap foglalatokkal szinte bármilyen MX-kompatibilis kapcsoló behelyezhető csavarhúzó nélkül, a QMK/VIA firmware teljes remappinget és makrózást tesz lehetővé. RGB háttérvilágítás, Bluetooth 5.1 és USB-C kábeles mód – asztali géphez és tablethez egyaránt használható. Az alumínium keret stabilitást és prémium megjelenést biztosít.',                                                                                                                'https://image.alza.cz/products/KCHRON30HU/KCHRON30HU.jpg?width=500&height=500',    7, 5,  34990.00, 0.860, 35),
(28, 'E016', 'ASUS TUF Gaming VG27AQL1A 27"', 'Az ASUS TUF Gaming VG27AQL1A a versenyszintű gaming és a kreativitás határán egyensúlyoz. A 27 colos QHD IPS panel 170 Hz-es frissítési rátával és 1 ms válaszidővel folyékony képet ad, G-Sync Compatible és FreeSync Premium Pro támogatással. Az ELMB Sync technológia egyidejű mozgásszinkronizálást és motion blur csökkentést biztosít. HDR10 és 130% sRGB lefedéssel kreatív munkához is elegendő, az ergonomikus állvány teljesen dönthető és forgatható.',                                                                                                                                 'https://images.euronics.hu/product_images/800x600/resize/1_ats7x339.jpg?v=3',   3, 4, 129990.00, 6.200, 15),
(29, 'E017', 'Samsung Odyssey G5 27"', 'A Samsung Odyssey G5 az ívelt gaming monitorok megfizethetőbb csúcsa. Az 1000R görbületű 27 colos VA panel szinte teljesen lefedi a látómezőt, a 165 Hz és 1 ms válaszidő versenyszintű élményt biztosít. QHD felbontás, AMD FreeSync Premium és HDR10 – nehéz ennél jobbat találni ezen az áron. Újratervezett állvány kábelmenedzsmenttel és VESA-kompatibilis rögzítéssel.',                                                                                                                     'https://images.euronics.hu/product_images/800x600/resize/s1_gfnzsulc.jpg?v=4', 3, 4, 99990.00, 5.900, 20),
(30, 'E018', 'Canon EOS R10',        'A Canon EOS R10 a legjobb belépő tükör nélküli fényképezőgép azoknak, akik komolyan szeretnék elsajátítani a fotózást. A 24,2 MP-es APS-C szenzor és a DIGIC X processzor kiváló képminőséget biztosít, az autófókusz rendszer 651 zónán, arcfelismeréssel és állat-AF-fel is dolgozik. 4K/30fps videó, Full HD/120fps lassítás, 15 fps sorozatfelvétel – mindez kompakt, könnyű házban, 625 kép üzemidővel.',                                                                                                                                         'https://image.alza.cz/products/OC0989a3/OC0989a3.jpg?width=500&height=500',      5, 5, 249990.00, 0.429,  2),
(31, 'E019', 'Sony Alpha A6400',     'A Sony Alpha A6400 az Eye AF technológia miatt vált legendássá. A valós idejű szemfókusz portréknál, gyerekeknél és állatoknál egyaránt verhetetlen, 0,02 másodperces fókuszidővel. A 24,2 MP-es szenzor ISO 32000-ig kiterjeszthető tartományban is részletgazdag képet ad, 4K HDR videó és 1080p/120fps lassítással. A kihajtható LCD kijelző vlogoláshoz is ideális – kicsi, könnyű, az E-mount lencserendszer teljes választékával bővíthető.',                                                                                              'https://image.alza.cz/products/OS072i1m12/OS072i1m12.jpg?width=500&height=500',         5, 5, 269990.00, 0.403, 15),
(32, 'E020', 'GoPro Hero 12 Black',  'A GoPro Hero 12 Black az élményrögzítés legsokoldalúbb eszköze. 5,3K/60fps, 4K/120fps és 2,7K/240fps felvétel egyaránt elérhető, a HyperSmooth 6.0 stabilizáció rázkódás nélküli képet biztosít. Vízálló 10 méteres mélységig tok nélkül, 177 fokos látószög, Max Lens Mod 2.0 opcióval. Síeléshez, búvárkodáshoz, bringázáshoz és utazáshoz – ez a kamera mindenhova elkísér.',                                                                                           'https://image.alza.cz/products/OG012a1ce/OG012a1ce.jpg?width=500&height=500',       5, 5, 139990.00, 0.154,  0),
(34, 'E022', 'Samsung 990 Pro 1TB NVMe SSD', 'A Samsung 990 Pro a leggyorsabb fogyasztói NVMe SSD-k egyike. PCIe 4.0×4 buszon 7450/6900 MB/s szekvenciális olvasási és írási sebesség, TLC V-NAND technológiával és 600 TBW élettartam-garanciával. A dinamikus thermal guard megakadályozza a túlmelegedést hosszú átvitel során is. Ideális operációs rendszernek, játékok telepítéséhez és nagy fájlok kezeléséhez – PS5-tel és minden PCIe 4.0 M.2 slottal kompatibilis.',                                                                                                                                            'https://image.alza.cz/products/SAS990ep4/SAS990ep4.jpg?width=500&height=500',    7, 5,  29990.00, 0.010, 40),
(35, 'E023', 'TP-Link Archer AX55 WiFi 6 Router', 'Az Archer AX55 WiFi 6 routerrel az egész otthon lefedhető gyors és stabil internettel. Az OFDMA és MU-MIMO technológiák egyszerre több eszközzel kommunikálnak hatékonyan, csökkentve a torlódást és a késleltetést. 2,4 GHz-en 574 Mbps, 5 GHz-en 2402 Mbps összesített kapacitás, négy Gigabit LAN port és USB 3.0 hálózati meghajtóhoz. Beépített Trend Micro antivírus védelemmel, szülői felügyelettel és QoS beállítással.',                                                                                                                                   'https://image.alza.cz/products/TP23_007/TP23_007.jpg?width=500&height=500',       9, 5,  19990.00, 0.305, 25),
(36, 'E024', 'Apple Watch Series 9 (GPS, 45mm)', 'Az Apple Watch Series 9 a legjobb okosóra iPhone mellé. Az S9 chip Double Tap gesztust hoz: összezárva mutatóujját és hüvelykujját kezelni tudja az órát anélkül, hogy a másik kezével is hozzáérne. A mindig bekapcsolt Retina kijelző 2000 nit fényerővel napfényben is jól olvasható. EKG, véroxigén-szint mérés, alváskövetés, esésdetekció – egészségügyi és sportfunkciók teljeskörűen, IP6X porállósággal és 50 méteres vízállósággal.',                                                                                                                   'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQDY3ref_AV1?wid=800&hei=800&fmt=jpeg&qlt=90',     6, 3, 149990.00, 0.039, 22),
(37, 'E025', 'Amazon Echo Dot 5. generáció', 'Az Echo Dot 5 a legjobb belépő okosotthon eszköz. A megújult hangszóró erősebb basszust biztosít az előző generációhoz képest – zene, podcastok és rádiók közel hifi minőségben szólnak ebből az apró eszközből. Az Alexa hangsegéd vezérli az okosotthon többi eszközét, megválaszolja a kérdéseket és kezeli a naptárat. Beépített hőmérséklet szenzor, WiFi 6, Bluetooth 5.2 és 3,5 mm-es audió kimenet.',                                                                  'https://image.alza.cz/products/AMAECHDO5TH/AMAECHDO5TH.jpg?width=500&height=500',    6, 5,  14990.00, 0.304, 55),
(39, 'T002', 'Samsung Galaxy S23',   'A Galaxy S23 a tavalyi csúcstelefon, idei áron – és ez egyáltalán nem szégyen. A Snapdragon 8 Gen 2 valódi csúcsteljesítményt biztosít, az 50 MP-es háromkamerás rendszer éjszakai fotózásban különösen kiemelkedő. Az 1200 nit csúcsfényerejű Dynamic AMOLED 2X kijelző napfényben is tökéletesen olvasható. Kompakt, 168 grammos ház, IP68 vízállóság, 3900 mAh akku 25 W gyorstöltéssel – megbízható és elegáns.',                                                                                                            'https://s13emagst.akamaized.net/products/52576/52575504/images/res_675b5c9d6f650e7c7c6d275f906d8f6e.jpg?width=720&height=720&hash=BA59C6D73AB2704CC4825815A0759290',        1, 1, 219990.00, 0.168, 20),
(40, 'T003', 'Dell Inspiron 15',     'A Dell Inspiron 15 az egyszerű, megbízható mindennapi laptop – semmi extra, csak ami valóban szükséges. Az Intel Core i5 és 8 GB RAM elvégzi a napi feladatokat, az 512 GB SSD gyors rendszerindítást biztosít, a 15,6 colos FHD kijelző kényelmes felületet ad böngészéshez és videóhívásokhoz. USB-A, USB-C, HDMI és SD kártyaolvasó megtalálható a gépen, Windows 11 Home előtelepítve – megbízható belépő laptop otthoni és iskolai használatra.',                                                                                                  'https://images.euronics.hu/product_images/800x600/resize/1dell_140rqx64.png?v=3',   2, 2, 179990.00, 1.830, 18),
(41, 'T004', 'HP Pavilion 14',       'A HP Pavilion 14 kompakt és könnyű laptop napi feladatokhoz. Az AMD Ryzen 5 processzor és 8 GB RAM a legtöbb irodai és online feladatot gond nélkül elvégzi, a 14 colos FHD IPS kijelző éles és széleslátószögű képet ad. 256 GB NVMe SSD gyors töltési időt biztosít, USB-C, két USB-A, HDMI és SD kártyaolvasóval felszerelve. Windows 11 Home előtelepítve – kényelmes, hordozható választás mindennapi használatra.',                                                                                                     'https://images.euronics.hu/product_images/800x600/resize/1_0bxnxfwe.png?v=3',     2, 2, 159990.00, 1.550, 23);

SET FOREIGN_KEY_CHECKS = 1;
