-- products.sql – RaktarPro
-- REPLACE INTO: bármikor újrafuttatható, nem dob hibát.
-- Importálás előtt importáld a db_schema.sql-t!
-- Kategória IDs: 1=Mobil, 2=Laptop, 3=TV & Monitor, 4=Fejhallgató,
--                5=Fotózás, 6=Okoseszközök, 7=PC Kiegészítők, 8=Gaming, 9=Hálózat

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

REPLACE INTO `products`
  (`id`, `sku`, `name`, `description`, `image_url`, `category_id`, `supplier_id`, `unit_price`, `weight`, `stock`)
VALUES
(1,  'P001', 'iPhone 15 Pro',        'Ha komoly telefont keresel, az iPhone 15 Pro nehezen megkerülhető. Titánium kerete könnyű és tartós egyszerre, a 48 MP-es kamera pedig szinte bármilyen fényviszonyban szép képet csinál. Az USB-C port végre egységes töltést jelent, az Action gombbal meg gyorsan előhívhatsz bármit.',         './imgs/iphone-15-pro.jpg',      1, 1, 589999.00, 0.187, 21),
(2,  'P002', 'Samsung Galaxy S24 Ultra', 'Az S24 Ultra az a telefon, amit ha egyszer kézbe veszel, nehéz letenni. A beépített S Pen minden más kiegészítőt feleslegessé tesz, a 200 MP-es kamera pedig annyira részletes képeket készít, hogy utólag is tudod vágni, közelíteni.',                                                           './imgs/samsung-s24-ultra.jpg',  1, 1, 469999.00, 0.232, 22),
(3,  'P003', 'ASUS ROG Strix G16 (2024)', 'Ha gaming laptopot keresel, de nem akarsz kompromisszumot kötni a teljesítménnyel, az ROG Strix G16 jó választás. Az RTX 4060 videokártya simán elboldogul a modern játékokkal, a 165 Hz-es kijelző pedig valóban érezhetően simább képet ad.',                                                  './imgs/asus-rog-strix.jpg',     8, 2, 749999.00, 2.500,  4),
(4,  'P004', 'MacBook Air M2 (2023)', 'A MacBook Air M2 az a laptop, amit szinte mindenki szeretne, aki Macet akar. Ventilátor nincs benne, tehát teljesen csendben működik, mégis meglepően gyors. Egész napra elég az akkuja, 1.24 kilós, és a kijelző gyönyörű.',                                                                       './imgs/macbook-air-m2.jpg',     2, 2, 549999.00, 1.240, 24),
(5,  'P005', 'Dell XPS 13 Plus (2023)', 'Az XPS 13 Plus az a laptop, amit a dizájnja miatt is megszeretsz. Szinte nincs kerete a kijelzőnek, a billentyűzeten nincs hagyományos érintőpad. Könnyű, stílusos, és az OLED panel olyan képet mutat, hogy egyszer sem fogod nézni az órádat.',                                               './imgs/dell-xps-13-plus.jpg',   2, 2, 699999.00, 1.240, 25),
(6,  'P006', 'HP Pavilion 15-eh3 (2023)', 'Ha egyszerűen csak egy jól működő, megbízható laptopot keresel mindennapi használatra, a HP Pavilion 15 pontosan erre való. Nagy a kijelzője, kényelmes a billentyűzete, és elég erős böngészéshez, dokumentumokhoz, videóhívásokhoz.',                                                         './imgs/hp-pavilion-15.jpg',     2, 2, 299999.00, 1.750, 26),
(7,  'P007', 'Lenovo ThinkPad X1 Carbon Gen 11', 'A ThinkPad X1 Carbon az a laptop, amit az irodai emberek évek óta esküdnek rá. Alig több mint egy kiló, mégis katonai teszteket állt ki. Az OLED kijelző gyönyörű, a billentyűzet a legjobb laptopbillentyűzetek közé tartozik.',                                                    './imgs/thinkpad-x1.jpg',        2, 2, 799999.00, 1.120,  3),
(8,  'P008', 'Sony WH-1000XM5',      'Ha sokat utazol vagy zajos helyen dolgozol, a WH-1000XM5 az, amit kerestek. A zajszűrése annyira hatékony, hogy repülőn is úgy érzed, mintha egy hangstúdióban ülnél. A párnák puhák, órákon át kényelmes viselni, a hang mély és részletgazdag.',                                              './imgs/sony-wh1000xm5.jpg',     4, 3, 129999.00, 0.250, 28),
(9,  'P009', 'Apple AirPods Pro 2. gen', 'Az AirPods Pro 2 az a fülhallgató, amit egyszer felteszel, aztán nem akarod levenni. A zajszűrés meglepően hatásos, a térhangzás filmekhez és zenéhez egyaránt élvezetes. Az USB-C tok bárhol tölthető, és a teljes rendszer IP54 minősítéssel rendelkezik.',                                  './imgs/airpods-pro-2.jpg',      4, 3, 109999.00, 0.061, 29),
(10, 'P010', 'JBL Charge 5',         'A JBL Charge 5 az a bluetooth hangszóró, ami mindenhova jön veled. IP67 védettséggel nem kell félni az esőtől. 20 óra akkumulátor, mély bassz és közepes méret – pontosan annyi, amennyit egy jó hordozható hangszórótól elvársz.',                                                              './imgs/jbl-charge-5.jpg',       4, 3,  54999.00, 0.960, 30),
(12, 'P012', 'LG OLED C3 65"',       'Az LG OLED C3 az egyik legjobb televízió, amit pénzért venni lehet. Az OLED panel minden pixele önmaga világít, így a fekete tényleg fekete, és a kontraszt végtelen. Filmekhez, sorozatokhoz, és komoly játékosoknak egyaránt az első választás.',                                                './imgs/lg-oled-c3-65.jpg',      3, 4, 899999.00, 18.500,  5),
(13, 'E001', 'iPhone 15',            'Az iPhone 15 az első iPhone USB-C csatlakozóval. A 48 MP-es kamera jelentős ugrás a korábbi modellekhez képest, az A16 chip pedig gyors és hatékony. Ha nem kell minden a Próból, ez az okos választás.',                                                                                      './imgs/iphone-15.jpg',          1, 1, 399999.00, 0.171, 40),
(14, 'E002', 'Samsung Galaxy S24',   'A Galaxy S24 a Samsung belépőszintű csúcstelefonja 2024-ben. Snapdragon 8 Gen 3 chip, 50 MP-es kamera, és Galaxy AI funkciók – mindez kompakt, 167 grammos házban. 120 Hz-es kijelző, 5G, IP68.',                                                                                          './imgs/samsung-s24.jpg',        1, 1, 319999.00, 0.167, 35),
(15, 'E003', 'Xiaomi Redmi Note 13 Pro', 'A Redmi Note 13 Pro az ár-érték kategória egyik legjobb telefonja. 200 MP-es kamera, AMOLED kijelző, 67 W-os töltés – ezeket a számokat más márkáknál dupla áron kapod.',                                                                                                               './imgs/xiaomi-redmi.jpg',       1, 1,  99999.00, 0.187, 45),
(16, 'E004', 'Google Pixel 8',       'A Pixel 8 a legtisztább Android élményt adja – friss frissítések 7 évig, Tensor G3 chip, és a legjobb kameraalgoritmus a piacon. 50 MP-es főkamera, Magic Eraser, Kíséreti Fotó funkció.',                                                                                                 './imgs/google-pixel-8.jpg',     1, 1, 289999.00, 0.187, 32),
(17, 'E005', 'MacBook Air M2',       'A MacBook Air M2 a legjobb mindennapi laptop, ha Macet akarsz. Csendes, gyors, egész napos akkumulátor. Nincs szellőző, mégis minden feladattal megbirkózik.',                                                                                                                                './imgs/macbook-air-m2-2.jpg',   2, 2, 549999.00, 1.240, 20),
(18, 'E006', 'Dell XPS 13',          'Az XPS 13 a Dell prémium ultrabookja, minimális kerettel és OLED kijelzővel. Könnyű, gyors és gyönyörű – utazáshoz és irodai munkához egyaránt tökéletes.',                                                                                                                                  './imgs/dell-xps-13.jpg',        2, 2, 649999.00, 1.170, 18),
(19, 'E007', 'Lenovo ThinkPad E14 Gen 5', 'A ThinkPad E14 a megbízható irodai laptop, amit Lenovo évtizedek óta tökéletesít. Ryzen processzor, kényelmes billentyűzet, ujjlenyomatolvasó és megbízható felépítés.',                                                                                                               './imgs/thinkpad-e14.jpg',       2, 2, 349999.00, 1.590, 22),
(20, 'E008', 'HP Envy 15',           'A HP Envy 15 a kreatívoknak és az igényes felhasználóknak szól. 4K OLED kijelző, erős processzor, és 5 MP-es webkamera Windows Hello arcfelismeréssel.',                                                                                                                                      './imgs/hp-envy-15.jpg',         2, 2, 499999.00, 1.990,  0),
(22, 'E010', 'LG 65" OLED TV',       'Az LG OLED tévék a tökéletes fekete és végtelen kontraszt szimbólumai. 65 colos, 4K, Dolby Vision, Dolby Atmos, és 4 HDMI 2.1 port játékosoknak. Ha egyszer OLED-et látsz, nincs visszaút.',                                                                                               './imgs/lg-oled-65.jpg',         3, 4, 799999.00, 19.500, 10),
(23, 'E011', 'Sony WH-1000XM5',      'Ugyanaz a világ legjobb zajszűrős fejhallgatója, kicsit más kialakításban. 30 óra akku, Multipoint Bluetooth, 8 mikrofon a kristálytiszta hívásokhoz.',                                                                                                                                       './imgs/sony-wh1000xm5-2.jpg',   4, 3, 129999.00, 0.250, 25),
(24, 'E012', 'Apple AirPods Pro 2. gen', 'Az AirPods Pro 2 a legjobb iOS-kompatibilis fülhallgató. Adaptive Transparency, Spatial Audio, USB-C töltőtok. Ha iPhone-od van, ez a természetes választás.',                                                                                                                          './imgs/airpods-pro-2-2.jpg',    4, 3, 109999.00, 0.061, 30),
(25, 'E013', 'JBL Charge 5',         'A JBL Charge 5 mindenhova jön veled – vízálló, tartós, erős hang. 20 óra lejátszás, PartyBoost több hangszóróhoz, és USB-A kimenet a telefon töltéséhez.',                                                                                                                                   './imgs/jbl-charge-5-2.jpg',     4, 3,  54999.00, 0.960, 28),
(26, 'E014', 'Logitech MX Master 3S', 'Az MX Master 3S a legjobb irodai egér. Darkfield szenzor üvegen is működik, MagSpeed görgő egy másodperc alatt lapozza át a dokumentumot, és 70 napig bírja egy töltéssel.',                                                                                                               './imgs/logitech-mx-master.jpg', 7, 5,  44999.00, 0.141, 50),
(27, 'E015', 'Keychron K8 Pro TKL',  'A Keychron K8 Pro a mechanikus billentyűzet-rajongók kedvence. Hot-swap foglalatokkal bármilyen kapcsolót berakhat, RGB háttérvilágítás, alumínium keret, és Bluetooth 5.1.',                                                                                                                './imgs/keychron-k8-pro.jpg',    7, 5,  59999.00, 0.860, 35),
(28, 'E016', 'ASUS TUF Gaming VG27AQL1A 27"', 'A TUF Gaming monitor 27 colos QHD IPS panelt kínál 170 Hz-es frissítési rátával. G-Sync Compatible és FreeSync Premium, 1 ms válaszidő, HDR400.',                                                                                                                                 './imgs/asus-tuf-monitor.jpg',   3, 4, 149999.00, 6.200, 15),
(29, 'E017', 'Samsung Odyssey G5 27"', 'A Samsung Odyssey G5 ívelt VA panel 1000R görbülettel. 165 Hz, 1 ms, QHD felbontás – mindezt kompetitív áron. Gaming monitornak nehéz jobbat találni ezen az áron.',                                                                                                                     './imgs/samsung-odyssey-g5.jpg', 3, 4, 119999.00, 5.900, 20),
(30, 'E018', 'Canon EOS R10',        'A Canon EOS R10 a legjobb belépő tükör nélküli fényképezőgép. 24 MP APS-C szenzor, 23 kép/mp, 4K videó, és Eye AF – mindez kompakt, könnyű házban.',                                                                                                                                         './imgs/canon-eos-r10.jpg',      5, 5, 329999.00, 0.429,  2),
(31, 'E019', 'Sony Alpha A6400',     'A Sony A6400 az Eye AF technológia miatt vált legendássá. Portréfotókhoz, gyerekekhez, állatokhoz – bármilyen mozgó alanyhoz ez a legokosabb választás. 24 MP, 4K videó, forgatható kijelző.',                                                                                              './imgs/sony-a6400.jpg',         5, 5, 279999.00, 0.403, 15),
(32, 'E020', 'GoPro Hero 12 Black',  'A GoPro Hero 12 a kalandok kamerája. 5.3K videó, vízálló 10 méterig tok nélkül, beépített GPS és Horizon Lock. Ha síelsz, búvárkodol, bringázol vagy utazol – ez a kamera mindenhova jön veled.',                                                                                           './imgs/gopro-hero12.jpg',       5, 5, 169999.00, 0.154,  0),
(34, 'E022', 'Samsung 990 Pro 1TB NVMe SSD', 'A Samsung 990 Pro a leggyorsabb fogyasztói SSD, amit ma kapni lehet. 7450 MB/s olvasási sebesség PCIe 4.0-val, és Samsung garanciával.',                                                                                                                                            './imgs/samsung-990-pro.jpg',    7, 5,  34999.00, 0.010, 40),
(35, 'E023', 'TP-Link Archer AX55 WiFi 6 Router', 'Az Archer AX55 WiFi 6 routerrel a teljes otthon lefedhető gyors és stabil internettel. AX3000 sebesség, 4 antenna, USB 3.0 NAS funkcióval.',                                                                                                                                   './imgs/tp-link-ax55.jpg',       9, 5,  24999.00, 0.305, 25),
(36, 'E024', 'Apple Watch Series 9 (GPS, 45mm)', 'Az Apple Watch Series 9 a legjobb okosóra iPhone mellé. EKG, vér oxigénszint mérés, Double Tap gesztus, és Always-On kijelző. 18 óra akku, WR50 vízállóság.',                                                                                                                   './imgs/apple-watch-s9.jpg',     6, 3, 179999.00, 0.039, 22),
(37, 'E025', 'Amazon Echo Dot 5. generáció', 'Az Echo Dot 5 a legjobb belépő okosotthon eszköz. Alexa segítségével zenét játszhat, okoseszközöket vezérelhet, és kérdésekre válaszolhat. Beépített hőmérséklet szenzor és jobb hang mint az előző generációban.',                                                                  './imgs/amazon-echo-dot.jpg',    6, 5,  14999.00, 0.304, 55),
(39, 'T002', 'Samsung Galaxy S23',   'A Galaxy S23 a tavalyi csúcstelefon, idei áron. Snapdragon 8 Gen 2, 50 MP kamera, kompakt 6,1 colos méret. Ha nem kell a legújabb, de flagshipet akarsz – ez az okos vásárlás.',                                                                                                            './imgs/samsung-s23.jpg',        1, 1, 259999.00, 0.168, 20),
(40, 'T003', 'Dell Inspiron 15',     'A Dell Inspiron 15 az egyszerű, megbízható mindennapi laptop. Intel Core i5, 8 GB RAM, 512 GB SSD – semmi extra, csak ami kell. Böngészéshez, dokumentumokhoz, videóhívásokhoz tökéletes.',                                                                                                  './imgs/dell-inspiron-15.jpg',   2, 2, 219999.00, 1.830, 18),
(41, 'T004', 'HP Pavilion 14',       'A HP Pavilion 14 kisebb és könnyebb, mint a 15 colos társa. 14 colos micro-edge kijelző, kényelmes billentyűzet, és a HP True Vision kamera videokonferenciákhoz is rendesen teljesít.',                                                                                                     './imgs/hp-pavilion-14.jpg',     2, 2, 199999.00, 1.550, 23);

SET FOREIGN_KEY_CHECKS = 1;
